[package]
name = "tiny-web"
version = "0.1.0"
authors = ["chuantang <chuantang.gu@17zuoye.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
